import Head from 'next/head'
import Image from 'next/image'
import { useEffect } from 'react';

import CustomImage from '../components/CustomImage/CustomImage';
import styles from '../styles/Home.module.css'

export default function Home() {
  // if (typeof window !== 'undefined') {
  //   // Здесь вы можете использовать объект window
  //   console.log(window.dataLayer);
  // }
  useEffect(() => {
    // Добавление кастомного события
    window.dataLayer.push({
      event: 'myCustomEvent',
      eventCategory: 'Category',
      eventAction: 'Action',
      eventLabel: 'Label',
    });
    console.log(window.dataLayer);
    console.log('after sending the event...')
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.grid}>
          <CustomImage imageName="image1"/>
          <CustomImage imageName="image2"/>
          <CustomImage imageName="image3"/>
          <CustomImage imageName="image4"/>
          <CustomImage imageName="image5"/>
          <CustomImage imageName="image6"/>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
